### ISSUE TITLE
Small typo, great work!

### ISSUE THREAD

**Issue by rulojuka** [lfsigreja/Imersao-Dev-Alura#1]
https://github.com/lfsigreja/Imersao-Dev-Alura/blob/f12b83bd5e5b62809ea301ffff517e6864ea00c1/Certificado/index.html#L19

Good job, man! Keep it up!

**Comment by lfsigreja** [comment]
Valeu Godz! Vamo que vamo!

**Comment by rulojuka** [comment]
Não sei se você entendeu exatamente... Mas tá escrito errado ali :) A issue foi realmente uma issue de verdade...
`Procut Owner` -> `Product Owner` :smile:
